/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.maxeltr.homeMq2t;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import ru.maxeltr.homeMq2t.Config.Config;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        ConfigurableApplicationContext applicationContext = SpringApplication.run(App.class, args);
        Config config = (Config) applicationContext.getBean("config");
        config.readConfigFromFile();
        System.out.println(config.getProperty("host", "1"));
    }
}
