/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.maxeltr.homeMq2t;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import ru.maxeltr.homeMq2t.Config.AppProperties;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        ConfigurableApplicationContext applicationContext = SpringApplication.run(App.class, args);
//        AppProperties appProperty = (AppProperties) applicationContext.getBean("appProperty");
//        System.out.println(appProperty.toString());
//        Logger logger = LoggerFactory.getLogger(App.class);
//        logger.trace("trace log infooooo");
//        logger.warn("warn log infooooo");

    }
}
